### ISSUE TITLE
Error using env_create()

### ISSUE THREAD

**Issue by zeeshan5k** [paulhendricks/gym-R#12]
Hi there
I am receiving an error when i run the below line
instance_id <- env_create(client, env_id)

the error is 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server
can you please help. 
i am using the localhost ip as mentioned in the example
I have already checked the firewall settings
Kinly help

**Comment by mikemcgraw17** [comment]
Did you figure out what the issue was for this? I am having the same problem.
